# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c56354a21e776c9023240c65053d0cfe00784f58cd0d846f43f344948adbeceb22645a3fa97c19ca02b13fc731fda1789ee70963a7d3e6266aca93cd6749a28a

test:
  secret_key_base: 8c241f043357a07206c4999dfd5f761561fdd2375d8ceed95669807be0e6dbc25de482a873f4682c431a2a556dc9005fdf1a1fa2ea2cb8d753016eb970da50b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
